#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antaeus.BL.Test
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="m_antaeus_temp")]
	public partial class DBTempDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBTempDataContext() : 
				base(global::Antaeus.BL.Test.Properties.Settings.Default.m_antaeus_tempConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTempDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTempDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTempDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTempDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TEMP_CR> TEMP_CRs
		{
			get
			{
				return this.GetTable<TEMP_CR>();
			}
		}
		
		public System.Data.Linq.Table<TEMP_SC> TEMP_SCs
		{
			get
			{
				return this.GetTable<TEMP_SC>();
			}
		}
	}
	
	[Table(Name="dbo.TEMP_CR")]
	public partial class TEMP_CR
	{
		
		private int _QUES_ID;
		
		private string _QUES_CONTENT;
		
		private string _QUES_A;
		
		private string _QUES_B;
		
		private string _QUES_C;
		
		private string _QUES_D;
		
		private string _QUES_E;
		
		private string _QUES_CORRECT;
		
		private byte _QUES_TYPE;
		
		private double _QUES_RATE;
		
		private string _QUES_SOURCE;
		
		private string _QUES_ANSWER;
		
		private string _QUES_MARK;
		
		private string _QUES_QUESTION;
		
		private bool _QUES_PLACE;
		
		public TEMP_CR()
		{
		}
		
		[Column(Storage="_QUES_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int QUES_ID
		{
			get
			{
				return this._QUES_ID;
			}
			set
			{
				if ((this._QUES_ID != value))
				{
					this._QUES_ID = value;
				}
			}
		}
		
		[Column(Storage="_QUES_CONTENT", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string QUES_CONTENT
		{
			get
			{
				return this._QUES_CONTENT;
			}
			set
			{
				if ((this._QUES_CONTENT != value))
				{
					this._QUES_CONTENT = value;
				}
			}
		}
		
		[Column(Storage="_QUES_A", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_A
		{
			get
			{
				return this._QUES_A;
			}
			set
			{
				if ((this._QUES_A != value))
				{
					this._QUES_A = value;
				}
			}
		}
		
		[Column(Storage="_QUES_B", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_B
		{
			get
			{
				return this._QUES_B;
			}
			set
			{
				if ((this._QUES_B != value))
				{
					this._QUES_B = value;
				}
			}
		}
		
		[Column(Storage="_QUES_C", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_C
		{
			get
			{
				return this._QUES_C;
			}
			set
			{
				if ((this._QUES_C != value))
				{
					this._QUES_C = value;
				}
			}
		}
		
		[Column(Storage="_QUES_D", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_D
		{
			get
			{
				return this._QUES_D;
			}
			set
			{
				if ((this._QUES_D != value))
				{
					this._QUES_D = value;
				}
			}
		}
		
		[Column(Storage="_QUES_E", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_E
		{
			get
			{
				return this._QUES_E;
			}
			set
			{
				if ((this._QUES_E != value))
				{
					this._QUES_E = value;
				}
			}
		}
		
		[Column(Storage="_QUES_CORRECT", DbType="NChar(10)")]
		public string QUES_CORRECT
		{
			get
			{
				return this._QUES_CORRECT;
			}
			set
			{
				if ((this._QUES_CORRECT != value))
				{
					this._QUES_CORRECT = value;
				}
			}
		}
		
		[Column(Storage="_QUES_TYPE", DbType="TinyInt NOT NULL")]
		public byte QUES_TYPE
		{
			get
			{
				return this._QUES_TYPE;
			}
			set
			{
				if ((this._QUES_TYPE != value))
				{
					this._QUES_TYPE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_RATE", DbType="Float NOT NULL")]
		public double QUES_RATE
		{
			get
			{
				return this._QUES_RATE;
			}
			set
			{
				if ((this._QUES_RATE != value))
				{
					this._QUES_RATE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_SOURCE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string QUES_SOURCE
		{
			get
			{
				return this._QUES_SOURCE;
			}
			set
			{
				if ((this._QUES_SOURCE != value))
				{
					this._QUES_SOURCE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_ANSWER", DbType="NVarChar(MAX)")]
		public string QUES_ANSWER
		{
			get
			{
				return this._QUES_ANSWER;
			}
			set
			{
				if ((this._QUES_ANSWER != value))
				{
					this._QUES_ANSWER = value;
				}
			}
		}
		
		[Column(Storage="_QUES_MARK", DbType="NVarChar(1000)")]
		public string QUES_MARK
		{
			get
			{
				return this._QUES_MARK;
			}
			set
			{
				if ((this._QUES_MARK != value))
				{
					this._QUES_MARK = value;
				}
			}
		}
		
		[Column(Storage="_QUES_QUESTION", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string QUES_QUESTION
		{
			get
			{
				return this._QUES_QUESTION;
			}
			set
			{
				if ((this._QUES_QUESTION != value))
				{
					this._QUES_QUESTION = value;
				}
			}
		}
		
		[Column(Storage="_QUES_PLACE", DbType="Bit NOT NULL")]
		public bool QUES_PLACE
		{
			get
			{
				return this._QUES_PLACE;
			}
			set
			{
				if ((this._QUES_PLACE != value))
				{
					this._QUES_PLACE = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.TEMP_SC")]
	public partial class TEMP_SC
	{
		
		private int _QUES_ID;
		
		private string _QUES_CONTENT;
		
		private string _QUES_A;
		
		private string _QUES_B;
		
		private string _QUES_C;
		
		private string _QUES_D;
		
		private string _QUES_E;
		
		private string _QUES_CORRECT;
		
		private byte _QUES_TYPE;
		
		private double _QUES_RATE;
		
		private string _QUES_SOURCE;
		
		private string _QUES_ANSWER;
		
		private string _QUES_MARK;
		
		public TEMP_SC()
		{
		}
		
		[Column(Storage="_QUES_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int QUES_ID
		{
			get
			{
				return this._QUES_ID;
			}
			set
			{
				if ((this._QUES_ID != value))
				{
					this._QUES_ID = value;
				}
			}
		}
		
		[Column(Storage="_QUES_CONTENT", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string QUES_CONTENT
		{
			get
			{
				return this._QUES_CONTENT;
			}
			set
			{
				if ((this._QUES_CONTENT != value))
				{
					this._QUES_CONTENT = value;
				}
			}
		}
		
		[Column(Storage="_QUES_A", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_A
		{
			get
			{
				return this._QUES_A;
			}
			set
			{
				if ((this._QUES_A != value))
				{
					this._QUES_A = value;
				}
			}
		}
		
		[Column(Storage="_QUES_B", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_B
		{
			get
			{
				return this._QUES_B;
			}
			set
			{
				if ((this._QUES_B != value))
				{
					this._QUES_B = value;
				}
			}
		}
		
		[Column(Storage="_QUES_C", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_C
		{
			get
			{
				return this._QUES_C;
			}
			set
			{
				if ((this._QUES_C != value))
				{
					this._QUES_C = value;
				}
			}
		}
		
		[Column(Storage="_QUES_D", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_D
		{
			get
			{
				return this._QUES_D;
			}
			set
			{
				if ((this._QUES_D != value))
				{
					this._QUES_D = value;
				}
			}
		}
		
		[Column(Storage="_QUES_E", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string QUES_E
		{
			get
			{
				return this._QUES_E;
			}
			set
			{
				if ((this._QUES_E != value))
				{
					this._QUES_E = value;
				}
			}
		}
		
		[Column(Storage="_QUES_CORRECT", DbType="NChar(10)")]
		public string QUES_CORRECT
		{
			get
			{
				return this._QUES_CORRECT;
			}
			set
			{
				if ((this._QUES_CORRECT != value))
				{
					this._QUES_CORRECT = value;
				}
			}
		}
		
		[Column(Storage="_QUES_TYPE", DbType="TinyInt NOT NULL")]
		public byte QUES_TYPE
		{
			get
			{
				return this._QUES_TYPE;
			}
			set
			{
				if ((this._QUES_TYPE != value))
				{
					this._QUES_TYPE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_RATE", DbType="Float NOT NULL")]
		public double QUES_RATE
		{
			get
			{
				return this._QUES_RATE;
			}
			set
			{
				if ((this._QUES_RATE != value))
				{
					this._QUES_RATE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_SOURCE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string QUES_SOURCE
		{
			get
			{
				return this._QUES_SOURCE;
			}
			set
			{
				if ((this._QUES_SOURCE != value))
				{
					this._QUES_SOURCE = value;
				}
			}
		}
		
		[Column(Storage="_QUES_ANSWER", DbType="NVarChar(MAX)")]
		public string QUES_ANSWER
		{
			get
			{
				return this._QUES_ANSWER;
			}
			set
			{
				if ((this._QUES_ANSWER != value))
				{
					this._QUES_ANSWER = value;
				}
			}
		}
		
		[Column(Storage="_QUES_MARK", DbType="NVarChar(1000)")]
		public string QUES_MARK
		{
			get
			{
				return this._QUES_MARK;
			}
			set
			{
				if ((this._QUES_MARK != value))
				{
					this._QUES_MARK = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
