//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antaeus.ORM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-LYNNING-02;Initial Catalog=Antaeus2.Database;Integrated Security=" +
            "True")]
        public string Antaeus2_DatabaseConnectionString {
            get {
                return ((string)(this["Antaeus2_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-LYNNING-02;Initial Catalog=Antaeus_0925_Test;Integrated Security=" +
            "True")]
        public string Antaeus_0925_TestConnectionString {
            get {
                return ((string)(this["Antaeus_0925_TestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-LYNNING-02;Initial Catalog=Antaeus_1011_Test;Integrated Security=" +
            "True")]
        public string Antaeus_1011_TestConnectionString {
            get {
                return ((string)(this["Antaeus_1011_TestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-SHMSCOM-01\\SQLEXPRESS;Initial Catalog=Antaeus_1011;Integrated Sec" +
            "urity=True")]
        public string Antaeus_1011ConnectionString {
            get {
                return ((string)(this["Antaeus_1011ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-SHMSCOM-01\\SQLEXPRESS;Initial Catalog=Antaeus_DB;Integrated Secur" +
            "ity=True")]
        public string Antaeus_DBConnectionString {
            get {
                return ((string)(this["Antaeus_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZIZ-LYNNING-LV\\SQLEXPRESS;Initial Catalog=Antaeus_DB;Integrated Secur" +
            "ity=True")]
        public string Antaeus_DBConnectionString1 {
            get {
                return ((string)(this["Antaeus_DBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=211.99.2.167;Initial Catalog=Antaeus_DB;Persist Security Info=True;Us" +
            "er ID=ans;Password=123456")]
        public string Antaeus_DBConnectionString2 {
            get {
                return ((string)(this["Antaeus_DBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\github\\Antaeus\\Antaeus\\Antaeus\\App_D" +
            "ata\\Antaeus_DB.mdf;Integrated Security=True;User Instance=True")]
        public string Antaeus_DBConnectionString3 {
            get {
                return ((string)(this["Antaeus_DBConnectionString3"]));
            }
        }
    }
}
