ALTER TABLE [dbo].[QB]
    ADD CONSTRAINT [PK_QB] PRIMARY KEY CLUSTERED ([QuestionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

