ALTER TABLE [dbo].[Rate]
    ADD CONSTRAINT [PK_Rate] PRIMARY KEY CLUSTERED ([RateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

