ALTER TABLE [dbo].[Wiki]
    ADD CONSTRAINT [PK_Wiki] PRIMARY KEY CLUSTERED ([KID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

